/**
 * POST /api/reports/export
 *
 * Downloads selected Salesforce reports using the native Analytics API endpoints.
 * Mirrors export_report_excel_native() and export_selected_reports_to_zip_concurrent_excel()
 * from report_exporter/exporter.py.
 *
 * KEY INSIGHT: Salesforce has a native Excel download endpoint — we just set the
 * Accept header and get back the exact .xlsx the user sees in the UI, with all
 * groupings, subtotals, merged cells, and formatting already built.
 * No factMap parsing. No SheetJS formatting. Just a straight binary download.
 *
 * Excel endpoint: GET /analytics/reports/{reportId}
 *   Headers: { Accept: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }
 *
 * CSV endpoint:  GET /analytics/reports/{reportId}?export=1&enc=UTF-8&fileFormat=csv
 *
 * Body: { reportIds: string[], format: 'excel' | 'csv', maxConcurrent?: number }
 */

import JSZip from 'jszip'
import { getSession } from '@/lib/session'
import { SalesforceClient } from '@/lib/salesforce/client'
import { createSSEStream } from '@/lib/streaming/sse'
import { generateJobId, storeResult } from '@/lib/jobs/store'
import { formatRuntime, makeTimestamp } from '@/lib/config'

const EXCEL_CONTENT_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
const EXCEL_ACCEPT       = EXCEL_CONTENT_TYPE

/** Mirrors safe_filename() from exporter.py */
function safeFilename(name, ext = '') {
  return String(name || 'Report')
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, '_')
    .replace(/\.+$/, '')
    .slice(0, 100)
    .trim() + ext
}

/**
 * Download a report as native Excel (.xlsx).
 * Mirrors export_report_excel_native() in exporter.py exactly:
 *   URL  = /services/data/vXX/analytics/reports/{reportId}
 *   Accept = application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
 */
async function downloadReportExcel(client, reportId) {
  const url = `${client.instanceUrl}/services/data/v${client.apiVersion}/analytics/reports/${reportId}`

  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${client.accessToken}`,
      Accept:        EXCEL_ACCEPT,
    },
    signal: AbortSignal.timeout(180_000),
  })

  if (!res.ok) {
    const text = await res.text()
    if (text.includes('login.salesforce.com') || text.includes('ec=302')) {
      throw new Error('Session expired or invalid — please reconnect')
    }
    if (text.includes('do not have access') || res.status === 403) {
      throw new Error('Access denied to this report')
    }
    if (res.status === 404) {
      throw new Error('Report not found or deleted')
    }
    throw new Error(`HTTP ${res.status}: ${text.slice(0, 120)}`)
  }

  const buffer = Buffer.from(await res.arrayBuffer())

  // Validate it's a real Excel file — must start with PK (ZIP magic bytes)
  // Mirrors: if not response.content.startswith(b'PK') → raise Exception
  if (buffer[0] !== 0x50 || buffer[1] !== 0x4B) {
    const preview = buffer.slice(0, 200).toString('utf8')
    if (preview.includes('API version') || preview.includes('minimum')) {
      throw new Error('Report Excel download requires API v39+. Try CSV format.')
    }
    throw new Error(`Non-Excel response received: ${preview.slice(0, 80)}`)
  }

  return buffer
}

/**
 * Download a report as CSV.
 * Mirrors export_report_csv() in exporter.py.
 * Also strips the Salesforce footer lines (mirrors clean_csv_footer()).
 */
async function downloadReportCSV(client, reportId) {
  const url = `${client.instanceUrl}/services/data/v${client.apiVersion}/analytics/reports/${reportId}?export=1&enc=UTF-8&fileFormat=csv`

  const res = await fetch(url, {
    headers: { Authorization: `Bearer ${client.accessToken}` },
    signal:  AbortSignal.timeout(120_000),
  })

  if (!res.ok) throw new Error(`CSV download failed: HTTP ${res.status}`)

  const text = await res.text()

  // Strip the Salesforce footer (mirrors clean_csv_footer in exporter.py):
  // "Generated By: ...", blank lines, "Confidential Information..."
  const lines       = text.split('\n')
  const footerStart = lines.findIndex(l =>
    /^"?Generated By:/i.test(l.trim()) ||
    /^"?Confidential/i.test(l.trim())
  )
  const cleaned = footerStart > 0 ? lines.slice(0, footerStart).join('\n') : text

  return Buffer.from(cleaned.trim(), 'utf-8')
}

/** Concurrent download pool — mirrors ThreadPoolExecutor in Python */
async function downloadConcurrently(items, processItem, maxConcurrent = 5) {
  const queue = [...items]
  const results = []
  async function worker() {
    while (queue.length > 0) {
      const item = queue.shift()
      if (!item) break
      results.push(await processItem(item))
    }
  }
  await Promise.all(Array.from({ length: Math.min(maxConcurrent, items.length) }, worker))
  return results
}

// ─────────────────────────────────────────────────────────────────────────────

export async function POST(request) {
  const { reportIds = [], format = 'excel', maxConcurrent = 5 } = await request.json()

  const session = await getSession()
  if (!session.accessToken) {
    return Response.json({ error: 'Not authenticated' }, { status: 401 })
  }
  if (!reportIds.length) {
    return Response.json({ error: 'Select at least one report to export.' }, { status: 400 })
  }

  const { response, emit, end } = createSSEStream()

  ;(async () => {
    try {
      const client  = SalesforceClient.fromSession(session)
      const jobId   = generateJobId()
      const startMs = Date.now()

      emit.info(`=== Report Exporter ===`)
      emit.info(`Reports: ${reportIds.length} | Format: ${format === 'excel' ? 'Native Excel (.xlsx)' : 'CSV'} | Concurrency: ${maxConcurrent}`)

      // Fetch report names for display and filenames
      const chunks = []
      for (let i = 0; i < reportIds.length; i += 200) {
        chunks.push(reportIds.slice(i, i + 200))
      }
      const reportMap = new Map()
      for (const chunk of chunks) {
        try {
          const { records } = await client.queryAll(
            `SELECT Id, Name, FolderName FROM Report WHERE Id IN (${chunk.map(id => `'${id}'`).join(', ')})`
          )
          for (const r of records) {
            reportMap.set(r.Id, { name: r.Name, folderName: r.FolderName || '' })
          }
        } catch {}
      }

      const zip       = new JSZip()
      const succeeded = []
      const failed    = []
      let   dlCount   = 0

      // Download all reports concurrently
      await downloadConcurrently(reportIds, async (reportId) => {
        const meta    = reportMap.get(reportId) || { name: reportId, folderName: '' }
        dlCount++
        const pct     = Math.round((dlCount / reportIds.length) * 90) + 5
        const elapsed = (Date.now() - startMs) / 1000

        emit.progress(pct, `[${dlCount}/${reportIds.length}] ${meta.name}…`, elapsed)

        try {
          const buffer = format === 'excel'
            ? await downloadReportExcel(client, reportId)
            : await downloadReportCSV(client, reportId)

          const ext      = format === 'excel' ? '.xlsx' : '.csv'
          const filename = safeFilename(meta.name, ext)
          const prefix   = meta.folderName ? `${safeFilename(meta.folderName)}/` : ''

          zip.file(`${prefix}${filename}`, buffer)
          succeeded.push({ id: reportId, name: meta.name, sizeKb: Math.round(buffer.byteLength / 1024) })
          emit.success(`  ✓ ${meta.name} (${Math.round(buffer.byteLength / 1024)} KB)`)

        } catch (err) {
          failed.push({ id: reportId, name: meta.name, error: err.message })
          emit.error(`  ✗ ${meta.name}: ${err.message}`)
        }
      }, maxConcurrent)

      if (succeeded.length === 0) {
        emit.error('No reports were downloaded successfully.')
        return
      }

      emit.progress(96, 'Packaging output…')

      // Single Excel report — serve directly without ZIP wrapper
      let finalBuffer, finalFilename, contentType

      if (reportIds.length === 1 && succeeded.length === 1 && format === 'excel') {
        const onlyFile = zip.files[Object.keys(zip.files)[0]]
        finalBuffer    = await onlyFile.async('nodebuffer')
        finalFilename  = safeFilename(succeeded[0].name, `_${makeTimestamp()}.xlsx`)
        contentType    = EXCEL_CONTENT_TYPE
      } else {
        finalBuffer   = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } })
        finalFilename  = `Reports_Export_${makeTimestamp()}.zip`
        contentType    = 'application/zip'
      }

      storeResult(jobId, { buffer: finalBuffer, filename: finalFilename, contentType })

      const elapsed  = (Date.now() - startMs) / 1000
      const runtime  = formatRuntime(elapsed)
      const statsObj = {
        totalDocuments:      reportIds.length,
        successfulDownloads: succeeded.length,
        failedDownloads:     failed.length,
        totalSizeBytes:      succeeded.reduce((s, r) => s + r.sizeKb * 1024, 0),
        runtimeFormatted:    runtime,
        failedFiles:         failed.map(f => ({ filename: f.name, reason: f.error })),
      }

      emit.done(`/api/reports/download/${jobId}`, statsObj)
      emit.success(`=== Done in ${runtime}: ${succeeded.length} exported, ${failed.length} failed ===`)

    } catch (err) {
      if (err.code === 'SESSION_EXPIRED') {
        emit.error('Session expired. Please reconnect to Salesforce.')
      } else {
        emit.error(`Export failed: ${err.message}`)
      }
    } finally {
      end()
    }
  })()

  return response
}
